allowBuilds:
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - pg-connection-string@2.14.0
  - pg-protocol@1.15.0
  - pg@8.22.0
